version: '3'

services:
  product-service:
    build: ./product
    ports:
      - 5001:80
    # Problem with user
    volumes:
      - ./product:/usr/src/app:z
  website:
    image: php:apache
    ports:
      - 5000:80
    volumes:
      - ./website:/var/www/html:z
    depends_on:
      - product-service
